#ifndef SEQUENCER_CONSTANTS_H
#define SEQUENCER_CONSTANTS_H

#define MODE_SEQUENCER 1
#define MODE_PITCH 2
#define MODE_PLAY 3

#define SCALE_LENGTH 7

#define BIT_OVERFLOW 0b100000000
#define LAST_BIT 0b10000000

#define TEMPO_POTENTIOMETER_MIN 1
#define TEMPO_POTENTIOMETER_MAX 10

#define CLOCK_GATE_POTENTIOMETER_MIN 1
#define CLOCK_GATE_POTENTIOMETER_MAX 10

#endif
